server:
  port: 2333
  address: 0.0.0.0

lavalink:
  plugins:
    - dependency: "dev.lavalink.youtube:youtube-plugin:ff634d161ee4de95102cfcd725554a60bec6e5cf"
      repository: "https://maven.lavalink.dev/snapshots"
      snapshot: true
  server:
    password: "musicbot_lavalink_pass"
    sources:
      youtube: false
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: true
    bufferDurationMs: 400
    frameBufferDurationMs: 5000
    playerUpdateInterval: 5

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - WEB
      - ANDROID_VR

logging:
  level:
    root: INFO
    lavalink: INFO
    dev.lavalink.youtube: DEBUG
